# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81447e18fe498a992d2f55aee1153b686992f098715a3ca2a477dc77e0ad804c8440f36c10f95a47e63d3f7ad186b71893ff6d9ae0eb12efa3048cc9e0a99b6d

test:
  secret_key_base: 42f22481f9b2c05c1e3b6311298cb54e962a48396fd3a31aec7b67a684fde0e5182fb9644e84e0190ca0a4e7be47086c2007612272f126cccfc4299559a13820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
